#cloud-config
# Template: The placeholder {{HETZNER_SSH_PUBLIC_KEY}} is replaced from .env
# Use: make hetzner-cloud-init (renders to cloud-init.rendered.yml)

timezone: Europe/Amsterdam
package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose-plugin
  - fail2ban
  - ufw
  - unattended-upgrades
  - apt-listchanges

users:
  - name: app
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - {{HETZNER_SSH_PUBLIC_KEY}}

ssh_pwauth: false

write_files:
  - path: /etc/ssh/sshd_config.d/10-hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no
      UsePAM yes
      X11Forwarding no
      AllowAgentForwarding no
      AllowTcpForwarding no
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-Time "03:30";
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }

runcmd:
  # UFW: Default Policies & Regeln
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw --force enable

  # Docker & Fail2ban aktivieren
  - systemctl daemon-reload
  - systemctl enable docker
  - systemctl restart docker
  - systemctl enable fail2ban
  - systemctl restart fail2ban

  # SSH neu laden, damit Hardening greift
  - systemctl reload ssh || systemctl restart ssh

  # Unattended-Upgrades aktivieren
  - systemctl enable unattended-upgrades
  - systemctl start unattended-upgrades
